// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: player.proto

#include "player.pb.h"
#include "player.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ue4 {

static const char* Player_method_names[] = {
  "/ue4.Player/GetLocation",
};

std::unique_ptr< Player::Stub> Player::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Player::Stub> stub(new Player::Stub(channel));
  return stub;
}

Player::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetLocation_(Player_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Player::Stub::GetLocation(::grpc::ClientContext* context, const ::ue4::LocationRequest& request, ::ue4::Location* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetLocation_, context, request, response);
}

void Player::Stub::experimental_async::GetLocation(::grpc::ClientContext* context, const ::ue4::LocationRequest* request, ::ue4::Location* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetLocation_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::ue4::Location>* Player::Stub::AsyncGetLocationRaw(::grpc::ClientContext* context, const ::ue4::LocationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ue4::Location>::Create(channel_.get(), cq, rpcmethod_GetLocation_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ue4::Location>* Player::Stub::PrepareAsyncGetLocationRaw(::grpc::ClientContext* context, const ::ue4::LocationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ue4::Location>::Create(channel_.get(), cq, rpcmethod_GetLocation_, context, request, false);
}

Player::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Player_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Player::Service, ::ue4::LocationRequest, ::ue4::Location>(
          std::mem_fn(&Player::Service::GetLocation), this)));
}

Player::Service::~Service() {
}

::grpc::Status Player::Service::GetLocation(::grpc::ServerContext* context, const ::ue4::LocationRequest* request, ::ue4::Location* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ue4

